default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: golangci-lint-fmt
        name: golangci-lint fmt --diff
        entry: golangci-lint fmt --diff
        language: system
        types: [go]
        pass_filenames: false
        stages: [pre-commit]

      - id: task-check
        name: task check
        entry: task check
        language: system
        pass_filenames: false
        stages: [pre-push]
